### ISSUE TITLE
Automatically select textarea

### ISSUE THREAD

**Issue by potato4d** [TomoyaShibata/markdown_link_generator_for_chrome#1]
## Need 

When open extension window, Extension selects its own text area.

**Comment by TomoyaShibata** [comment]
@potato4d 

Thanks!!
Created feature and PR https://github.com/TomoyaShibata/markdown_link_generator_for_chrome/pull/2

Does this meet your needs?

## Before

![before](https://user-images.githubusercontent.com/2193123/32000640-4d31273a-b9d2-11e7-8f52-ecd6a9fb786e.gif)

## After

![after](https://user-images.githubusercontent.com/2193123/32000643-504d0d62-b9d2-11e7-823c-64900b3bb9b3.gif)

**Comment by potato4d** [comment]
@TomoyaShibata
Awesome! 😍

**Comment by TomoyaShibata** [comment]
Merge done!!
This feature will be released shortly 😃
